### ISSUE TITLE
Class ScheduleWebServiceView contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ISchedulePage::BindViewableResourceReservations)

### ISSUE THREAD

**Issue by JohnVillalovos** [LibreBooking/app#343]
When running LibreBooking and tried to hit the API endpoint I get this in the log:

```
[app] | [Fri May 10 13:08:51.927255 2024] [php:error] [pid 84] [client 10.89.0.25:59502] PHP Fatal error:  Class ScheduleWebServiceView contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ISchedulePage::BindViewableResourceReservations) in /var/www/html/WebServices/SchedulesWebService.php on line 169
```

And when looking at the code it does appear the `ScheduleWebServiceView` does not implement the method `BindViewableResourceReservations`

**Comment by JohnVillalovos** [comment]
My best guess is that this was caused by #307
